@echo off

:: FILE WITH LIST OF FILES TO BE COPIED
SET INPUT=C:\temp\in.txt
:: TARGET LOCATION OF FILES TO BE COPIED TO
SET TARGET=C:\temp\target\
:: FILE WITH LIST OF XCOPY COMMANDS BASED ON INPUT
SET OUTPUT=C:\temp\out.cmd

IF EXIST %OUTPUT% DEL %OUTPUT%
FOR /F "TOKENS=* DELIMS=" %%E IN ('TYPE %INPUT%') DO (
	ECHO XCOPY /F /Y "%%E" "%TARGET%" >> %OUTPUT%
)

